from tkinter import *
from tkinter import messagebox

top=Tk()
l1=Label(top,text="First Name")
l1.grid(row=0,column=0)
t1=Entry(top,bd=5) 
t1.grid(row=0,column=1)
l2=Label(top,text="Last Name")
l2.grid(row=1,column=0)
t2=Entry(top,bd=5) 
t2.grid(row=1,column=1)
l3=Label(top,text="Contact Number")
l3.grid(row=2,column=0)
t3=Entry(top,bd=5) 
t3.grid(row=2,column=1)
l4=Label(top,text="Gender")
l4.grid(row=3,column=0)
var=IntVar()
r1=Radiobutton(top,text="Male",variable=var,value=1)
r2=Radiobutton(top,text="Female",variable=var,value=2)
r1.grid(row=3,column=1)
r2.grid(row=3,column=2)
b1=Button(top,text="Register")
b1.grid(row=4,column=0)
top.geometry('500x500')
