from tkinter import *
from tkinter import messagebox
top=Tk()
top.title("Python")
def Hello():
    print("Hello")
def Hello1():
    #messagebox.askokcancel("Information","Button is clicked")
    #messagebox.showinfo("Information","Button is clicked")
    #messagebox.showwarning("Information","Button is clicked")
    #messagebox.showerror("Information","Button is clicked")
    messagebox.askquestion("Information","Button is clicked")
l1=Label(top,text="Enter the Name",bg='pink',fg='green')
l1.grid(row=0,column=0)
t1=Entry(top,bd=5) 
t1.grid(row=0,column=1)
b1=Button(top,text="Submit",bg='pink',fg='blue',command=Hello1)
b1.grid(row=1,column=0)
var=IntVar()
r1=Radiobutton(top,text="Male",variable=var,value=1)
r2=Radiobutton(top,text="Female",variable=var,value=2)
r1.grid(row=2,column=0)
r2.grid(row=2,column=1)
c1=Checkbutton(top,text="Sports")
c2=Checkbutton(top,text="Music")
c1.grid(row=3,column=0)
c2.grid(row=3,column=1)
lb1=Listbox(top)
lb1.insert(1,"Python")
lb1.insert(2,"Java")
lb1.grid(row=4,column=0)
top.geometry('600x500')
