# Generated by Django 3.1.1 on 2020-12-30 08:21

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myapp', '0011_auto_20201230_1351'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turfs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('capacity', models.IntegerField()),
                ('description', models.CharField(max_length=1000)),
                ('stars', models.FloatField()),
                ('rate', models.IntegerField()),
                ('price', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None), max_length=7, size=None)),
                ('slots', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=15), size=None), max_length=7, size=None)),
                ('imageUrls', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('turf', models.OneToOneField(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, primary_key=True, serialize=False, to='turfs.turfs')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('address', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('pincode', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('day', models.IntegerField()),
                ('slot', models.IntegerField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('turf', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='turfs.turfs')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='myapp.users')),
            ],
        ),
    ]
