# Generated by Django 3.1.1 on 2020-12-30 15:42

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turfs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turfs',
            name='imageUrls',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), size=None),
        ),
    ]
