# Generated by Django 3.1.1 on 2021-01-02 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turfs', '0004_auto_20201230_2330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='day',
        ),
        migrations.AlterField(
            model_name='bookings',
            name='slot',
            field=models.CharField(max_length=20),
        ),
    ]
