# Generated by Django 3.1.1 on 2021-01-10 08:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turfs', '0005_auto_20210102_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='turfs',
            name='contact',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='turfs',
            name='users',
            field=models.IntegerField(default=0),
        ),
    ]
