# Generated by Django 3.1.1 on 2020-12-13 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20201213_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='contact',
            field=models.BigIntegerField(unique=True),
        ),
    ]
