# Generated by Django 3.1.1 on 2020-12-18 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20201214_1405'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('contact', models.BigIntegerField(unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('birthday', models.DateField(max_length=30)),
                ('otp', models.IntegerField(max_length=6)),
            ],
        ),
        migrations.AddField(
            model_name='users',
            name='authToken',
            field=models.CharField(default='noe', max_length=256),
            preserve_default=False,
        ),
    ]
