# Generated by Django 3.1.1 on 2020-12-18 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20201218_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempusers',
            name='otp',
            field=models.IntegerField(),
        ),
    ]
