# Generated by Django 3.1.1 on 2020-12-30 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20201219_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempusers',
            name='contact',
            field=models.BigIntegerField(),
        ),
    ]
