# Generated by Django 3.1.1 on 2020-12-30 15:42

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_auto_20201230_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='city',
            field=models.CharField(default='Mumbai', max_length=20),
        ),
        migrations.AlterField(
            model_name='users',
            name='authToken',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), max_length=3, size=None),
        ),
    ]
