# Generated by Django 3.1.1 on 2020-12-30 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_auto_20201230_2313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='favturf',
            new_name='favturfs',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='ratings',
            new_name='stars',
        ),
    ]
