# Generated by Django 3.1.1 on 2021-01-05 10:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_auto_20201230_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='favturfs',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=[], size=None),
        ),
        migrations.AlterField(
            model_name='users',
            name='stars',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None), blank=True, default=[], size=None),
        ),
    ]
