# Generated by Django 3.1.1 on 2021-01-13 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_auto_20210105_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='owner',
            field=models.BooleanField(default=False),
        ),
    ]
